### ISSUE TITLE
Using WSL Ubuntu, got an error:  m4 1.4.18 did not build

### ISSUE THREAD

**Issue by citystrawman** [shashanoid/Simpdf#13]
I tried to execute command brew install pdf2htmlEX and got error messages as follows:

> HOMEBREW_CC: gcc-9
HOMEBREW_CXX: g++-9
MAKEFLAGS: -j16
CMAKE_PREFIX_PATH: /home/linuxbrew/.linuxbrew
HOMEBREW_GIT: git
ACLOCAL_PATH: /home/linuxbrew/.linuxbrew/share/aclocal
PATH: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super:/usr/bin:/bin:/usr/sbin:/sbin
Error: m4 1.4.18 did not build
Logs:
     /home/lihang/.cache/Homebrew/Logs/m4/00.options.out
     /home/lihang/.cache/Homebrew/Logs/m4/01.configure
     /home/lihang/.cache/Homebrew/Logs/m4/02.make
     /home/lihang/.cache/Homebrew/Logs/m4/02.make.cc
     /home/lihang/.cache/Homebrew/Logs/m4/config.log
     /home/lihang/.cache/Homebrew/Logs/m4/01.configure.cc
READ THIS: https://docs.brew.sh/Troubleshooting

Then I tried to use brew install m4 and got errors as follows:

> ==> Downloading https://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.xz
Already downloaded: /home/lihang/.cache/Homebrew/downloads/bb74c92bda9bdc32be0653ca50751920ff35cfe8f329499d0bea86fbe66ce580--m4-1.4.18.tar.xz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/m4/1.4.18
==> make
Last 15 lines from /home/lihang/.cache/Homebrew/Logs/m4/02.make:
   92 |  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
      |   ^~~~~
make[3]: *** [Makefile:1915: freadahead.o] Error 1
make[3]: *** Waiting for unfinished jobs....
fseeko.c: In function 'rpl_fseeko':
fseeko.c:110:4: error: #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
  110 |   #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
      |    ^~~~~
make[3]: *** [Makefile:1915: fseeko.o] Error 1
make[3]: Leaving directory '/tmp/m4-20201024-24482-13va2rn/m4-1.4.18/lib'
make[2]: *** [Makefile:1674: all] Error 2
make[2]: Leaving directory '/tmp/m4-20201024-24482-13va2rn/m4-1.4.18/lib'
make[1]: *** [Makefile:1572: all-recursive] Error 1
make[1]: Leaving directory '/tmp/m4-20201024-24482-13va2rn/m4-1.4.18'
make: *** [Makefile:1528: all] Error 2
READ THIS: https://docs.brew.sh/Troubleshooting

unfamiliar with make, could anyone help me about it?

**Comment by Debdut** [comment]
This repo is not maintained anymore
